-- 코드를 입력하세요
SELECT a.FLAVOR FROM (
    SELECT FLAVOR, TOTAL_ORDER 
    FROM FIRST_HALF
    UNION
    SELECT FLAVOR, TOTAL_ORDER 
    FROM JULY
) a
GROUP BY a.FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3